CREATE TABLE IF NOT EXISTS master_data (
    "NO" INTEGER PRIMARY KEY,
    "SATUAN KERJA" TEXT,
    "SATKER" TEXT,
    "KODE SATKER_str" TEXT,
    "KPA" TEXT,
    "KODE UNIT" INTEGER,
    "UNIT KERJA" TEXT,
    "WILAYAH" TEXT,
    "KODE PPK" TEXT,
    "NAMA PPK" TEXT,
    "NIP PPK" TEXT
);
