-- SQL Script untuk membuat tabel berdasarkan file CSV/Excel

-- 1. Tabel Paket Anggaran Penyedia (dari paket-anggaran-penyedia_2026.csv)
CREATE TABLE IF NOT EXISTS public.paket_anggaran_penyedia (
    id_paket_anggaran_penyedia BIGINT PRIMARY KEY,
    kd_klpd TEXT,
    kd_satker_str TEXT,
    sumber_dana TEXT,
    tahun_anggaran_dana TEXT,
    status_delete_rup TEXT,
    status_aktif_rup TEXT,
    status_umumkan_rup TEXT,
    mak TEXT,
    pagu NUMERIC,
    kd_kegiatan TEXT,
    kd_rup BIGINT,
    kd_komponen TEXT,
    nama_satker TEXT,
    asal_dana TEXT,
    jenis_klpd TEXT,
    asal_dana_satker TEXT,
    jenis_dana_apbn TEXT,
    kd_satker BIGINT,
    nama_klpd TEXT,
    asal_dana_klpd TEXT,
    tahun_anggaran TEXT,
    last_update_ref TEXT,
    kd_rup_lokal TEXT,
    kd_subkegiatan TEXT
);

-- 2. Tabel Paket Anggaran Swakelola (dari paket-anggaran-swakelola_2026.csv)
CREATE TABLE IF NOT EXISTS public.paket_anggaran_swakelola (
    id_paket_anggaran_swakelola BIGINT PRIMARY KEY,
    kd_satker_str TEXT,
    kd_subkegiatan TEXT,
    tahun_anggaran TEXT,
    asal_dana_klpd TEXT,
    kd_komponen TEXT,
    kd_satker BIGINT,
    kd_rup_lokal TEXT,
    status_delete_rup TEXT,
    mak TEXT,
    tahun_anggaran_dana TEXT,
    jenis_klpd TEXT,
    kd_klpd TEXT,
    kd_rup BIGINT,
    pagu NUMERIC,
    asal_dana_satker TEXT,
    kd_kegiatan TEXT,
    status_umumkan_rup TEXT,
    nama_satker TEXT,
    sumber_dana TEXT,
    asal_dana TEXT,
    nama_klpd TEXT,
    jenis_dana_apbn TEXT,
    status_aktif_rup TEXT,
    last_update_ref TEXT
);

-- 3. Tabel Tender Selesai Nilai (dari tender-selesai-nilai_2025.xlsx)
CREATE TABLE IF NOT EXISTS public.tender_selesai_nilai (
    kd_tender TEXT PRIMARY KEY,
    jenis_klpd TEXT,
    nama_penyedia TEXT,
    hps NUMERIC,
    npwp_16_penyedia TEXT,
    tahun_anggaran TEXT,
    kd_klpd TEXT,
    kd_lpse TEXT,
    kd_rup_paket TEXT,
    kd_satker TEXT,
    nilai_pdn_kontrak NUMERIC,
    nilai_umk_kontrak NUMERIC,
    npwp_penyedia TEXT,
    nilai_negosiasi NUMERIC,
    psr_id TEXT,
    tgl_penetapan_pemenang TIMESTAMP,
    kd_paket TEXT,
    pagu NUMERIC,
    kd_penyedia TEXT,
    nama_klpd TEXT,
    nama_satker TEXT,
    tgl_pengumuman_tender TIMESTAMP,
    nilai_kontrak NUMERIC,
    nilai_penawaran NUMERIC,
    nilai_terkoreksi NUMERIC,
    last_update_ref TEXT
);
