CREATE TABLE IF NOT EXISTS api_pencatatan_swakelola (
    alasan_pembatalan TEXT,
    kd_lpse BIGINT,
    nama_ppk TEXT,
    sumber_dana TEXT,
    nama_paket TEXT,
    tgl_mulai_paket TIMESTAMPTZ,
    kd_swakelola_pct BIGINT PRIMARY KEY,
    nip_ppk TEXT,
    jenis_klpd TEXT,
    status_swakelola_pct TEXT,
    tahun_anggaran INTEGER,
    informasi_lainnya TEXT,
    nilai_pdn_pct NUMERIC,
    nilai_umk_pct NUMERIC,
    kd_satker_str TEXT,
    uraian_pekerjaan TEXT,
    kd_pkt_dce BIGINT,
    nama_klpd TEXT,
    nama_satker TEXT,
    kd_rup BIGINT,
    tgl_selesai_paket TIMESTAMPTZ,
    kd_satker BIGINT,
    tgl_buat_paket TIMESTAMPTZ,
    pagu NUMERIC,
    tipe_swakelola TEXT,
    status_swakelola_pct_ket TEXT,
    kd_klpd TEXT,
    total_realisasi NUMERIC,
    tipe_swakelola_nama TEXT,
    last_update_ref TEXT
);
